import * as stylex from "@stylexjs/stylex";
export const styles = stylex.create({
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 18,
		paddingBlock: 22,
	},
	brand: {
		display: "inline-flex",
		alignItems: "center",
		gap: 10,
		color: "#1a1b25",
	},
	mark: {
		width: 28,
		height: 28,
	},
	wordmark: {
		fontSize: 20,
		lineHeight: 1.2,
		fontWeight: 750,
		letterSpacing: ".02em",
	},
	headerRight: { display: "flex", alignItems: "center", gap: 16 },
	desktopOnly: { "@media (max-width: 540px)": { display: "none" } },
	tabsNav: {
		overflowX: "auto",
		overflowY: "clip",
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: "#f0f1f5",
		marginBottom: 24,
	},
	navLinks: {
		display: "flex",
		width: "fit-content",
		gap: 2,
		paddingTop: 4,
		marginBottom: -1,
	},
	navLink: {
		paddingBlock: 5,
		paddingInline: 12,
		borderBottomWidth: 2,
		borderBottomStyle: "solid",
		borderBottomColor: "transparent",
		color: "#9c9eab",
		fontSize: 13,
		fontWeight: 650,
		whiteSpace: "nowrap",
		outline: "none",
		":hover": { color: "#1a1b25" },
		":focus-visible": { boxShadow: "0 0 0 3px #ffd7b0" },
	},
	navLinkActive: { borderBottomColor: "#f48120", color: "#1a1b25" },
	footer: {
		marginTop: 40,
		paddingTop: 16,
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: "#f0f1f5",
		color: "#c2c4ce",
		fontSize: 11,
	},
	spacer: { flexGrow: 1 },
	filterToolbar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 10,
		flexWrap: "wrap",
		"@media (max-width: 600px)": { alignItems: "stretch" },
	},
	filterFields: {
		display: "grid",
		minWidth: 0,
		flexBasis: 0,
		flexGrow: 1,
		gridTemplateColumns:
			"minmax(150px, 1.4fr) minmax(110px, .8fr) minmax(150px, 1fr)",
		gap: 6,
		"@media (max-width: 600px)": {
			width: "100%",
			gridTemplateColumns: "1fr 1fr",
		},
	},
	filterProject: { "@media (max-width: 600px)": { gridColumn: "1 / -1" } },
	filterActions: {
		display: "flex",
		alignItems: "center",
		gap: 6,
		marginInlineStart: "auto",
		"@media (max-width: 600px)": {
			width: "100%",
			justifyContent: "space-between",
		},
	},
	checkboxLabel: {
		display: "inline-flex",
		alignItems: "center",
		gap: 8,
		color: "#6b6d7c",
		fontSize: 12,
		whiteSpace: "nowrap",
		cursor: "pointer",
	},
	eventTable: { minWidth: 600, tableLayout: "fixed" },
	eventProjectColumn: { width: 140 },
	eventLevelColumn: { width: 100 },
	eventTimeColumn: { width: 120 },
	eventTableMain: { minWidth: 0, overflow: "hidden" },
	eventTableLink: {
		position: "relative",
		zIndex: 1,
		display: "block",
		minWidth: 0,
		outline: "none",
	},
	eventTableTitle: {
		display: "flex",
		alignItems: "center",
		gap: 8,
		minWidth: 0,
		fontWeight: 500,
		lineHeight: 1.25,
	},
	eventTableBody: {
		display: "block",
		marginTop: 4,
		overflow: "hidden",
		color: "#686868",
		fontSize: 13,
		lineHeight: 1.25,
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	eventSilenced: {
		display: "block",
		marginTop: 5,
		color: "#686868",
		fontSize: 11,
	},
	eventTableTime: { textAlign: "right" },
	frameActions: { display: "flex", justifyContent: "flex-end" },
	eventRow: {
		display: "grid",
		gridTemplateColumns: "120px minmax(0, 1fr) 80px 64px",
		gap: 16,
		alignItems: "center",
		paddingBlock: 9,
		paddingInline: 10,
		borderRadius: 8,
		color: "#1a1b25",
		":hover": { backgroundColor: "#fafafc" },
		"@media (max-width: 600px)": {
			gridTemplateColumns: "1fr auto",
			gridTemplateRows: "auto auto",
		},
	},
	groupEventRow: { gridTemplateColumns: "minmax(0, 1fr) 80px 64px" },
	eventProject: {
		display: "flex",
		gap: 6,
		alignItems: "center",
		minWidth: 0,
		color: "#6b6d7c",
		fontSize: 13,
		"@media (max-width: 600px)": { gridColumn: 1, gridRow: 1 },
	},
	eventMain: {
		minWidth: 0,
		"@media (max-width: 600px)": { gridColumn: "1 / span 2", gridRow: 2 },
	},
	eventTitle: {
		display: "flex",
		alignItems: "baseline",
		gap: 8,
		minWidth: 0,
		fontSize: 15,
		lineHeight: 1.3,
		fontWeight: 650,
	},
	eventBody: {
		color: "#9c9eab",
		fontSize: 13,
		marginTop: 2,
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	count: {
		color: "#b45309",
		backgroundColor: "#fff3e8",
		borderRadius: 999,
		paddingBlock: 1,
		paddingInline: 8,
		fontSize: 12,
		flexShrink: 0,
	},
	eventLevel: { "@media (max-width: 600px)": { display: "none" } },
	eventTime: {
		color: "#9c9eab",
		fontSize: 11,
		textAlign: "right",
		"@media (max-width: 600px)": { gridColumn: 2, gridRow: 1 },
	},
	truncate: {
		overflow: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
	},
	crumbRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 10,
	},
	crumb: {
		display: "flex",
		alignItems: "center",
		gap: 8,
		color: "#6b6d7c",
		fontSize: 13,
		minWidth: 0,
	},
	link: { color: "#b45309", ":hover": { color: "#92400e" } },
	mono: {
		fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
		overflowWrap: "anywhere",
	},
	menu: {
		display: "flex",
		flexDirection: "column",
		gap: 4,
		padding: 10,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#f0f1f5",
		borderRadius: 10,
	},
	menuButton: {
		textAlign: "left",
		backgroundColor: "transparent",
		borderWidth: 0,
		color: "#1a1b25",
		paddingBlock: 8,
		paddingInline: 10,
		borderRadius: 8,
		fontSize: 13,
		":hover": { backgroundColor: "#fafafc" },
	},
	head: { display: "flex", flexDirection: "column", gap: 8 },
	h1: {
		fontSize: 20,
		lineHeight: 1.25,
		letterSpacing: "-.01em",
		overflowWrap: "anywhere",
	},
	meta: {
		display: "flex",
		gap: 8,
		alignItems: "center",
		flexWrap: "wrap",
		color: "#6b6d7c",
		fontSize: 13,
	},
	body: {
		color: "#6b6d7c",
		fontSize: 14,
		lineHeight: 1.5,
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
	},
	facts: {
		display: "grid",
		gridTemplateColumns: "1fr 1fr",
		gap: 8,
		marginTop: 12,
		paddingTop: 12,
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: "#f0f1f5",
		"@media (max-width: 600px)": { gridTemplateColumns: "1fr" },
	},
	fact: {
		minWidth: 0,
		display: "flex",
		flexDirection: "column",
		gap: 2,
		overflowWrap: "anywhere",
		fontSize: 13,
	},
	factKey: { color: "#9c9eab", fontSize: 11 },
	secondary: { color: "#6b6d7c", fontSize: 13, lineHeight: 1.6 },
	muted: { color: "#9c9eab", fontSize: 12, lineHeight: 1.5 },
	row: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
	rightActions: {
		display: "flex",
		justifyContent: "flex-end",
		gap: 8,
		marginTop: 16,
	},
	detailSection: {
		display: "flex",
		flexDirection: "column",
		gap: 8,
		paddingBlock: 12,
		paddingInline: 16,
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: "#f0f1f5",
		":first-child": { borderTopWidth: 0 },
	},
	detailSectionHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	detailPage: { display: "flex", flexDirection: "column", gap: 16 },
	detailPanel: { padding: 0, overflow: "hidden" },
	detailList: { padding: 8 },
	contextRow: {
		display: "grid",
		gridTemplateColumns: "140px minmax(0, 1fr)",
		gap: 12,
		paddingBlock: 5,
		fontSize: 13,
		"@media (max-width: 600px)": { gridTemplateColumns: "1fr" },
	},
	pillList: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 12 },
	pill: {
		display: "inline-flex",
		alignItems: "center",
		gap: 6,
		paddingBlock: 4,
		paddingInline: 10,
		borderRadius: 999,
		backgroundColor: "#fafafc",
		boxShadow: "inset 0 0 0 1px #e4e6ee",
		fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
		fontSize: 12,
	},
	pillAccent: { color: "#b45309", backgroundColor: "#fff3e8" },
	delivery: {
		display: "grid",
		gridTemplateColumns: "1fr auto 1fr auto",
		gap: 12,
		alignItems: "center",
		fontSize: 13,
		paddingBlock: 4,
		"@media (max-width: 600px)": { gridTemplateColumns: "1fr auto" },
	},
	mobileHide: { "@media (max-width: 600px)": { display: "none" } },
	right: { textAlign: "right", justifySelf: "end" },
	pageToolbar: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 16,
		flexWrap: "wrap",
	},
	grow: { flexGrow: 1, minWidth: 180 },
	projectTable: { minWidth: 560, tableLayout: "fixed" },
	projectNotificationsColumn: { width: 140 },
	projectCreatedColumn: { width: 110 },
	projectActionsColumn: { width: 100 },
	projectHead: { display: "flex", alignItems: "center", gap: 12 },
	projectText: { flexGrow: 1, minWidth: 0 },
	projectName: {
		display: "flex",
		alignItems: "baseline",
		gap: 8,
		minWidth: 0,
		fontSize: 15,
		fontWeight: 650,
		lineHeight: 1.4,
	},
	projectTableAction: { textAlign: "right" },
	projectSettingsCell: {
		paddingBlock: 0,
		paddingInline: 20,
		whiteSpace: "normal",
	},
	deviceTable: { minWidth: 560, tableLayout: "fixed" },
	deviceEnable: { display: "flex", alignItems: "center", gap: 10 },
	devicePushColumn: { width: 140 },
	deviceLastSeenColumn: { width: 120 },
	deviceActionsColumn: { width: 100 },
	deviceNameCell: { overflow: "hidden" },
	deviceTableAction: { textAlign: "right" },
	statusGrid: {
		display: "grid",
		gridTemplateColumns: "1fr 1fr",
		gap: 12,
		"@media (max-width: 600px)": { gridTemplateColumns: "1fr" },
	},
	settingsOverviewDetails: {
		marginTop: 20,
		paddingTop: 16,
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: "#f0f1f5",
	},
	settingsCompactForm: { marginTop: 12 },
	settingsPanel: { display: "flex", flexDirection: "column", gap: 16 },
	settingsPillList: { marginTop: 0 },
	silenceRow: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
		paddingBlock: 8,
		paddingInline: 10,
		borderRadius: 8,
		":hover": { backgroundColor: "#fafafc" },
	},
	silenceForm: {
		display: "flex",
		alignItems: "center",
		gap: 8,
		flexWrap: "wrap",
		marginTop: 16,
	},
	pillButton: {
		color: "inherit",
		backgroundColor: "transparent",
		borderWidth: 0,
		padding: 0,
	},
});
